import { useEffect, useState } from 'react'; import { Link, useParams } from 'react-router-dom';
import { adminGetReturn, adminUpdateReturn, type ApiReturn } from '../../lib/api'; import { C, F } from '../../theme'; import { useApp } from '../../state/AppContext'; import { PageHeader } from '../components/PageHeader';
const statuses = ['requested','approved','awaiting_item','received','inspected','resolved','rejected','customer_cancelled'];
export function ReturnDetail() { const { id } = useParams(); const { lang } = useApp(); const pt = lang === 'pt'; const [row,setRow]=useState<ApiReturn|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(false);
  useEffect(()=>{ if(id) adminGetReturn(id).then(setRow).catch(()=>setError(true)); },[id]);
  const update = async (patch: Partial<ApiReturn>) => { if(!row)return; setBusy(true); try { setRow(await adminUpdateReturn(row.id,patch)); } catch { setError(true); } finally { setBusy(false); } };
  if(!row)return <div style={{padding:28,color:error?C.danger:C.inkSoft}}>{error?'Unable to load return.':'Loading…'}</div>;
  return <div><PageHeader eyebrow={`${pt?'Devoluções':'Returns'} / ${row.returnNumber}`} title={row.status.replaceAll('_',' ')} subtitle={`${row.orderNumber} · ${row.customerName}`} backTo="/admin/devolucoes" backLabel={pt?'Voltar':'Back'} />
    <div style={{padding:'20px 28px 40px',display:'grid',gap:16}}><section style={card}><div style={heading}>{pt?'Estado e resolução':'Status & resolution'}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12}}><Field label={pt?'Estado':'Status'}><select value={row.status} disabled={busy} onChange={e=>update({status:e.target.value})} style={input}>{statuses.map(s=><option key={s} value={s}>{s.replaceAll('_',' ')}</option>)}</select></Field><Field label={pt?'Valor aprovado':'Approved value'}><input type="number" value={row.approvedAmount??0} onChange={e=>setRow({...row,approvedAmount:Number(e.target.value)})} onBlur={()=>update({approvedAmount:row.approvedAmount})} style={input}/></Field><Field label={pt?'Estado do reembolso':'Refund status'}><select value={row.refundStatus} onChange={e=>update({refundStatus:e.target.value})} style={input}>{['not_required','pending','completed','failed'].map(s=><option key={s}>{s}</option>)}</select></Field></div></section>
    <section style={card}><div style={heading}>{pt?'Artigos e inspeção':'Items & inspection'}</div>{row.items.map((item,i)=><div key={item.orderItemId} style={{padding:'12px 0',borderTop:i?`1px solid ${C.ruleLight}`:'none'}}><div style={{fontWeight:800,color:C.ink}}>{item.quantity}× {item.productName} {item.color||item.size?`· ${[item.color,item.size].filter(Boolean).join(' / ')}`:''}</div><div style={{fontSize:11,color:C.inkSoft,margin:'5px 0 10px'}}>Paid allocation: {item.refundableAmount} {row.currency}</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:10}}><Field label={pt?'Inspeção':'Inspection'}><select value={item.inspection||'pending'} onChange={e=>{const items=[...row.items];items[i]={...item,inspection:e.target.value as never};setRow({...row,items});}} style={input}><option value="pending">pending</option><option value="accepted">accepted</option><option value="rejected">rejected</option></select></Field><Field label={pt?'Quantidade a repor':'Restock quantity'}><input type="number" min={0} max={item.quantity} value={item.restockQuantity||0} onChange={e=>{const items=[...row.items];items[i]={...item,restockQuantity:Number(e.target.value)};setRow({...row,items});}} style={input}/></Field><Field label={pt?'Variante de substituição':'Replacement variant ID'}><input value={item.replacementVariantId||''} onChange={e=>{const items=[...row.items];items[i]={...item,replacementVariantId:e.target.value};setRow({...row,items});}} style={input}/></Field></div></div>)}<button disabled={busy} onClick={()=>update({items:row.items})} style={button}>{pt?'Guardar inspeção':'Save inspection'}</button></section>
    <section style={card}><div style={heading}>{pt?'Referências financeiras':'Financial references'}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><Field label="Refund reference"><input value={row.refundReference||''} onChange={e=>setRow({...row,refundReference:e.target.value})} onBlur={()=>update({refundReference:row.refundReference})} style={input}/></Field><Field label="Store credit code"><input value={row.storeCreditCode||''} onChange={e=>setRow({...row,storeCreditCode:e.target.value})} onBlur={()=>update({storeCreditCode:row.storeCreditCode})} style={input}/></Field></div>{row.replacementOrder&&<div style={{marginTop:12,fontSize:12}}>{pt?'Encomenda de substituição':'Replacement order'}: <Link to={`/admin/encomendas/${typeof row.replacementOrder==='object'?row.replacementOrder.id:row.replacementOrder}`}>{typeof row.replacementOrder==='object'?row.replacementOrder.orderNumber:row.replacementOrder}</Link></div>}</section>{error&&<div style={{color:C.danger}}>Save failed.</div>}</div></div>;
}
const card={background:C.paper,border:`1px solid ${C.ruleLight}`,borderRadius:8,padding:16} as const; const heading={fontFamily:F.display,fontWeight:800,color:C.goldDeep,marginBottom:14} as const; const input={width:'100%',padding:'10px',border:`1px solid ${C.rule}`,borderRadius:6,background:C.subtleBg} as const; const button={marginTop:14,padding:'10px 16px',background:C.black,color:C.onDarkGold,borderRadius:6,fontWeight:800} as const;
function Field({label,children}:{label:string;children:React.ReactNode}){return <label><div style={{fontSize:9,fontWeight:800,color:C.goldDeep,marginBottom:5,textTransform:'uppercase'}}>{label}</div>{children}</label>}
